---
input:
  type: RosInput
  tf_verbosity: 1
  clear_queue_on_fail: true
  inputs:
    left_cam:
      receiver: 
        type: ClosedSetImageReceiver
        # [关键修改] 允许 RGB 和深度图的时间戳有微小差异
        # 真实机器人数据几乎都需要开启这个！
        approximate_sync: true 
      sensor: 
        type: camera_info
        min_range: 0.1
        max_range: 10.0
        extrinsics: 
          type: ros
          robot_frame: acl_jackal2/base_link
features: {type: FeatureReceiver}